name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: echo "Atualizado automaticamente!"
